name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_PATH: 'sample/MyCalculator/MyCalculator.sln'
  TESTS_PATH: 'sample/MyCalculator/MyCalculator.Specs/MyCalculator.Specs.csproj'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore
    - name: Test
      run: dotnet test ${{ env.TESTS_PATH }} --no-build --verbosity normal
